---
- name: Reset k3s cluster
  hosts: k3s_cluster
  become: true
  
  tasks:
    - name: Run k3s uninstall
      command: /usr/local/bin/k3s-{{ 'uninstall' if k3s_control_node else 'agent-uninstall' }}.sh
      ignore_errors: yes
    
    - name: Remove directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/rancher
        - /var/lib/rancher
    
    - name: Reboot
      reboot:
